### ISSUE TITLE
Feature request: toggle hide/show inline css

### ISSUE THREAD

**Issue by ghost** [outofsync42/inline-css-color#3]
Hey, I use the extension a lot, its really usefull. Do you think is easy to add a little button that toggles the whole css string? The problem to solve is that sometimes you have so many styles in the element that the component ends up being huge. Maybe we could also add a button that show/hide all the styles in the file. What do you think? If you point me in the right direction, I could try to work on that too.

**Comment by outofsync42** [comment]
Glad you like the extension :) . However if you have that many properties in your style you should really move it to a class. I'm not sure where to point you for that since I don't have any experience with that type of functionality but I can look into it and see how difficult it might be to achieve. Maybe in the next week or so Ill have some time to look into it.

**Comment by ghost** [comment]
No, dont bother. I'm working on a new project in Svelte and my idea was to only use javascript to handle styles. That works  fine for simple css, but creates too much boilerplate for more complex things like using hover styles, media queries, etc. I will just close the issue with a big thanks for your work :)
